[controller]
domain = "test-chain-node1"
consensus_port = 50001
controller_port = 50004
crypto_port = 50005
enable_metrics = true
executor_port = 50002
metrics_port = 60004
network_port = 50000
node_address = 'example/node_address'
storage_port = 50003
validator_address = 'example/validator_address'

[controller.log_config]
max_level = "info"
filter = "info"
# rolling_file_path = "./logs"
service_name = "controller"
# agent_endpoint = "127.0.0.1:6831"

[genesis_block]
timestamp = 123456
prevhash = "0x010203040506"

[system_config]
version = 0
chain_id = "0x010203040506"
admin = "0x060504030201"
block_interval = 3
validators = ["0x01010101", "0x02020202"]
block_limit = 100
quota_limit = 1073741824
