[package]
name = "controller"
version = "6.1.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
log4rs = { version = "1.0", features = ["gzip"] }
clap = "3.0.0-beta.2"
git-version = "*"
tonic = "0.5"
prost = "0.8"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1.7"
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto", branch = "bath_send_txs_dev" }
futures = "0.3.15"
futures-util = "0.3.15"
rand = "0.8"
toml = "0.5.8"
serde = "1.0.126"
serde_derive = "1.0.126"
hex = "0.4.3"
crossbeam = "0.8.1"
backtrace = "0.3.60"
bincode = "1.3.3"
libsm = "0.4"
efficient-sm2 = "0.1"
rayon = "1.5"

[build-dependencies]
tonic-build = "0.5"

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1
