[package]
name = "controller"
version = "6.4.1"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
log4rs = { version = "1.0", features = ["gzip"] }
clap = { version = "3.1", features = ["derive"] }
tonic = "0.5"
prost = "0.8"
tokio = { version = "1.17", features = ["full"] }
rand = "0.8"
toml = "0.5"
serde = "1.0"
serde_derive = "1.0"
hex = "0.4"
backtrace = "0.3"

cloud-util = "0.2.0"
cita_cloud_proto = "6.4.0"
status_code = { package = "cloud-code", version = "0.2.1" }

[build-dependencies]
tonic-build = "0.5"

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1
