[package]
name = "controller"
version = "5.0.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
log4rs = { version = "*", features = ["gzip"] }
clap = "3.0.0-beta.2"
git-version = "*"
tonic = "*"
prost = "*"
tokio = { version = "*", features = ["full"] }
tokio-stream = "*"
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto", branch = "full_block_develop" }
futures-util = "*"
rand = "*"
toml = "*"
serde = "*"
serde_derive = "*"
hex = "*"
inotify = "*"
crossbeam = "*"
backtrace = "*"
bincode = "*"

[build-dependencies]
tonic-build = "*"

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1
