[package]
name = "controller"
version = "6.6.2"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
log4rs = { version = "1.2", features = ["gzip"] }
clap = { version = "4.0", features = ["derive"] }
tonic = "0.8"
prost = "0.11"
tokio = { version = "1.21", features = ["full"] }
rand = "0.8"
toml = "0.5"
serde = "1.0"
serde_derive = "1.0"
hex = "0.4"
backtrace = "0.3"
tower = "0.4.13"

cloud-util = { git = "https://github.com/cita-cloud/cloud-util" }
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto" }
status_code = { package = "cloud-code", git = "https://github.com/cita-cloud/status_code" }

[build-dependencies]
tonic-build = "0.8"

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1
