[package]
name = "controller"
version = "4.0.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
log4rs = { version = "1.0.0", features = ["gzip"] }
clap = "3.0.0-beta.2"
git-version = "0.3.4"
tonic = "0.4.1"
prost = "0.7.0"
tokio = { version = "1.4.0", features = ["full"] }
tokio-stream = "0.1.5"
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto", branch = "v4.0.0" }
futures-util = "0.3.13"
rand = "0.8.3"
toml = "0.5.8"
serde = "1.0.125"
serde_derive = "1.0.125"
hex = "0.4.3"
inotify = "0.9.2"
crossbeam = "0.8.0"
backtrace = "0.3.56"

[dev-dependencies]
tempdir = "0.3.7"


[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1
