name: Security Audit

on:
  push:
    branches:
      - master
    paths:
      - '**/Cargo.toml'
  schedule:
    - cron: '0 18 * * *' # run at 18 AM UTC. AM 2 utc+8

jobs:
  security-audit:
    runs-on: [self-hosted, Linux, alibaba-cloud]
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2

      - name: Audit Check
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
